### ISSUE TITLE
Zone clean-up?

### ISSUE THREAD

**Issue by raidenlal** [nergal/homeassistant-vacuum-viomi#34]
Hello there,
I have used viomi integration for several months, either from you, nergal, or from someone upstream or downstream, can't remember. However it stopped working so I moved to this viomi integration, because of how easy it is to download/update via HACS.

However this flavor of integration is missing zone clean-up, which I miss very much. Any ideas if you plan to add support? Or is it HASS issue? Or maybe I am doing something wrong?
I have used such definitions:
```
          service: xiaomi_viomi.clean_zone
          target:
            entity_id: vacuum.robot
          data:
            zone:
              - - -1.1 #left
                - 1.3 #up
                - 0.2 #right
                - 0.4 #down
            repeats: 1
```
Now the service is non-existent in this integration. ANY ideas? Thank you.
